pipeline {
    agent {
      node {
        // spin up a pod to run this build on
        label 'docker'
      }
    }
    options {
        timeout(time: 45, unit: 'MINUTES')
    }
    environment {
        REF_TAG = sh(returnStdout: true, script: "git describe --exact-match --tags HEAD || echo noTagMatches").trim()
    }
    stages {
        stage('Preamble') {
            steps {
                echo 'REF TAG: ${env.REF_TAG}'
            }
        }
        stage('Build docker image') {
            steps {
                sh 'make -f ./openshift/Makefile build'
            }
        }
        stage('Run tests in container') {
            steps {
                sh 'make -f ./openshift/Makefile test'
            }
        }
        stage('Run linter in container') {
            steps {
                sh 'make -f ./openshift/Makefile lint'
            }
        }
        stage('Push to Docker repo') {
            steps {
                sh 'make -f ./openshift/Makefile push'
            }
        }
        stage('Tag INT') {
            steps {
                sh 'make -f ./openshift/Makefile tag-int'
            }
        }
        stage('Deploy INT') {
            steps {
                sh 'make -f ./openshift/Makefile deploy-int'
            }
        }
        stage('Test INT') {
            steps {
                sh 'make -f ./openshift/Makefile test-int'
            }
        }
        stage('Tag QAS') {
            steps {
                sh 'make -f ./openshift/Makefile tag-qas'
            }
        }
        stage('Deploy qas') {
            steps {
                sh 'make -f ./openshift/Makefile deploy-qas'
            }
        }
        stage('Test QAS') {
            steps {
                sh 'make -f ./openshift/Makefile test-qas'
            }
        }
        stage('Tag and deploy PRD') {
            when {
                expression { env.REF_TAG != "noTagMatches" }
            }
            steps {
                echo 'Tag PRD'
                sh 'make -f ./openshift/Makefile tag-prd'
                echo 'Deploy PRD'
                sh 'make -f ./openshift/Makefile deploy-prd'
            }
        }
    }
    post {
        always {
            sh 'make -f ./openshift/Makefile post-clean'
            cleanWs()
        }
    }
}